# 硬盘的参数（用于格式化硬盘）
DISK_START = 200

BLOCK_BYTES = 512
INODE_BLOCK_SIZE = 822
DISK_BLOCK_SIZE = 16976
LRU_CACHE_LENGTH = 15

# 超级块
SUPERBLOCK_START = DISK_START + 0
SUPERBLOCK_BLOCKS = 2
SUPERBLOCK_BYTES = SUPERBLOCK_BLOCKS * BLOCK_BYTES

# Inode
INODE_START = SUPERBLOCK_START + 2
INODE_BYTES = 64
INODE_ROOT_NO = 0
INODE_PER_BLOCK = BLOCK_BYTES // INODE_BYTES
INODE_COUNT = INODE_BLOCK_SIZE * INODE_PER_BLOCK
# Inode里的目录项
INODE_DIRECTORY_ENTRY_COUNT = 10
INODE_SMALL_THRESHOLD = 6
INODE_LARGE_THRESHOLD = 8
INODE_HUGE_THRESHOLD = INODE_DIRECTORY_ENTRY_COUNT

# 数据区
DATA_START = INODE_START + INODE_BLOCK_SIZE
DATA_BLOCK_BYTES = BLOCK_BYTES
DATA_BLOCK_COUNT = DISK_BLOCK_SIZE - DATA_START
INT_PER_BLOCK = BLOCK_BYTES // 4

# 目录项
DIRECTORY_BYTES = 32
DIRECTORY_PER_BLOCK = BLOCK_BYTES // DIRECTORY_BYTES

# 文件索引块
FILE_INDEX_BYTES = 4
FILE_INDEX_BLOCK_BYTES = BLOCK_BYTES
FILE_INDEX_PER_BLOCK = FILE_INDEX_BLOCK_BYTES // FILE_INDEX_BYTES

# 根据Inode里的目录项的各项阈值，以及每个文件索引块里面能装多少索引，
# 计算出的几个阈值对应的索引数量
_SMALL_INDEX_COUNT = INODE_SMALL_THRESHOLD
_LARGE_INDEX_COUNT = INODE_LARGE_THRESHOLD - INODE_SMALL_THRESHOLD
_HUGE_INDEX_COUNT = INODE_HUGE_THRESHOLD - INODE_LARGE_THRESHOLD

FILE_INDEX_SMALL_THRESHOLD = _SMALL_INDEX_COUNT
FILE_INDEX_SMALL_LENGTH = FILE_INDEX_SMALL_THRESHOLD
FILE_INDEX_LARGE_THRESHOLD = FILE_INDEX_SMALL_THRESHOLD + _LARGE_INDEX_COUNT * FILE_INDEX_PER_BLOCK
FILE_INDEX_LARGE_LENGTH = FILE_INDEX_LARGE_THRESHOLD - FILE_INDEX_SMALL_THRESHOLD
FILE_INDEX_HUGE_THRESHOLD = FILE_INDEX_LARGE_THRESHOLD + _HUGE_INDEX_COUNT * FILE_INDEX_PER_BLOCK * FILE_INDEX_PER_BLOCK
FILE_INDEX_HUGE_LENGTH = FILE_INDEX_HUGE_THRESHOLD - FILE_INDEX_LARGE_THRESHOLD

FILE_SIZE_SMALL_THRESHOLD = FILE_INDEX_SMALL_THRESHOLD * BLOCK_BYTES
FILE_SIZE_LARGE_THRESHOLD = FILE_INDEX_LARGE_THRESHOLD * BLOCK_BYTES
FILE_SIZE_HUGE_THRESHOLD = FILE_INDEX_HUGE_THRESHOLD * BLOCK_BYTES

# 空闲盘块索引块
FREE_INDEX_BYTES = 4
FREE_INDEX_BLOCK_BYTES = BLOCK_BYTES
FREE_INDEX_PER_BLOCK = 100