## 以下是所有磁盘都一样的参数

# LRU缓存块数
LRU_CACHE_LENGTH = 15

# 扇区大小
BLOCK_BYTES = 512

# 超级块
SUPERBLOCK_BLOCKS = 2
SUPERBLOCK_BYTES = SUPERBLOCK_BLOCKS * BLOCK_BYTES
SUPERBLOCK_FREE_BLOCK = 100
SUPERBLOCK_FREE_INODE = 100

# Inode
INODE_BYTES = 64
INODE_ROOT_NO = 0
INODE_PER_BLOCK = BLOCK_BYTES // INODE_BYTES
# Inode里的目录项
INODE_DIRECTORY_ENTRY_COUNT = 10
INODE_SMALL_THRESHOLD = 6
INODE_LARGE_THRESHOLD = 8
INODE_HUGE_THRESHOLD = INODE_DIRECTORY_ENTRY_COUNT

# 数据区
DATA_BLOCK_BYTES = BLOCK_BYTES
INT_PER_BLOCK = BLOCK_BYTES // 4

# 目录项
DIRECTORY_BYTES = 32
DIRECTORY_PER_BLOCK = BLOCK_BYTES // DIRECTORY_BYTES

# 文件索引块
FILE_INDEX_BYTES = 4
FILE_INDEX_BLOCK_BYTES = BLOCK_BYTES
FILE_INDEX_PER_BLOCK = FILE_INDEX_BLOCK_BYTES // FILE_INDEX_BYTES

# 根据Inode里的目录项的各项阈值，以及每个文件索引块里面能装多少索引，
# 计算出的几个阈值对应的索引数量
_SMALL_INDEX_COUNT = INODE_SMALL_THRESHOLD
_LARGE_INDEX_COUNT = INODE_LARGE_THRESHOLD - INODE_SMALL_THRESHOLD
_HUGE_INDEX_COUNT = INODE_HUGE_THRESHOLD - INODE_LARGE_THRESHOLD

FILE_INDEX_SMALL_THRESHOLD = _SMALL_INDEX_COUNT
FILE_INDEX_LARGE_THRESHOLD = FILE_INDEX_SMALL_THRESHOLD + _LARGE_INDEX_COUNT * FILE_INDEX_PER_BLOCK
FILE_INDEX_HUGE_THRESHOLD = FILE_INDEX_LARGE_THRESHOLD + _HUGE_INDEX_COUNT * FILE_INDEX_PER_BLOCK * FILE_INDEX_PER_BLOCK

FILE_INDEX_SMALL_LENGTH = FILE_INDEX_SMALL_THRESHOLD
FILE_INDEX_LARGE_LENGTH = FILE_INDEX_LARGE_THRESHOLD - FILE_INDEX_SMALL_THRESHOLD
FILE_INDEX_HUGE_LENGTH = FILE_INDEX_HUGE_THRESHOLD - FILE_INDEX_LARGE_THRESHOLD

FILE_SIZE_SMALL_THRESHOLD = FILE_INDEX_SMALL_THRESHOLD * BLOCK_BYTES
FILE_SIZE_LARGE_THRESHOLD = FILE_INDEX_LARGE_THRESHOLD * BLOCK_BYTES
FILE_SIZE_HUGE_THRESHOLD = FILE_INDEX_HUGE_THRESHOLD * BLOCK_BYTES

# 空闲盘块索引块
FREE_INDEX_BYTES = 4
FREE_INDEX_BLOCK_BYTES = BLOCK_BYTES
FREE_INDEX_PER_BLOCK = 100

# 用于标识具有扩充数据的superblock的磁盘的魔数
MAGIC = b"febilly~"
