import constants as C

## 以下是需要计算得出的参数
## 初始为默认值

# 硬盘的参数（用于格式化硬盘）
DISK_START = 0
INODE_BLOCK_SIZE = 4096
DISK_BLOCK_SIZE = 32768

# 总字节数
TOTAL_BYTES = DISK_BLOCK_SIZE * C.BLOCK_BYTES

# 超级块
SUPERBLOCK_START = DISK_START

# Inode
INODE_START = SUPERBLOCK_START + C.SUPERBLOCK_BLOCKS
INODE_COUNT = INODE_BLOCK_SIZE * C.INODE_PER_BLOCK

# 数据区
DATA_START = INODE_START + INODE_BLOCK_SIZE
DATA_BLOCK_COUNT = DISK_BLOCK_SIZE - DATA_START

def init_constants(disk_start: int = 0, inode_block_size: int = 4096, disk_block_size: int = 32768) -> None:
    global DISK_START, INODE_BLOCK_SIZE, DISK_BLOCK_SIZE
    DISK_START = disk_start
    INODE_BLOCK_SIZE = inode_block_size
    DISK_BLOCK_SIZE = disk_block_size

    global TOTAL_BYTES, SUPERBLOCK_START, INODE_START, INODE_COUNT, DATA_START, DATA_BLOCK_COUNT
    TOTAL_BYTES = DISK_BLOCK_SIZE * C.BLOCK_BYTES
    SUPERBLOCK_START = DISK_START
    INODE_START = SUPERBLOCK_START + C.SUPERBLOCK_BLOCKS
    INODE_COUNT = INODE_BLOCK_SIZE * C.INODE_PER_BLOCK
    DATA_START = INODE_START + INODE_BLOCK_SIZE
    DATA_BLOCK_COUNT = DISK_BLOCK_SIZE - DATA_START
    